name: "postprocess"
backend: "python"
max_batch_size: 1
input [
    {
        name: "DL_MODEL_OUTPUT"
        data_type: TYPE_FP32
        dims: [-1, -1]
    }
]
input [
    {
        name: "PREPROCESSED_IMAGE_SHAPE"
        data_type: TYPE_INT32
        dims: [2]
    }
]
input [
    {
        name: "ORIGINAL_IMAGE_SHAPE"
        data_type: TYPE_INT32
        dims: [2]
    }
]
input [
    {
        name: "CONFIDENCE_TRESH"
        data_type: TYPE_FP64
        dims: [-1] 
        optional: True
    }
]
output [
    {
        name: "FINAL_OUTPUT"
        data_type: TYPE_STRING
        dims: [-1]
    }
]
instance_group [
{
    kind: KIND_CPU
}
]
